name: Build and Push Docker Image on New Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print working directory
      run: pwd

    - name: Download release asset
      uses: robinraju/release-downloader@v1.10
      with:
        repository: 'mdwajid095/kcctl'
        tag: ${{ github.event.release.tag_name }}
        fileName: 'v1.4-alpha.zip'

    - name: Download release asset
      uses: i3h/download-release-asset@v1
      with:
        owner: mdwajid095
        repo: kcctl
        tag: ${{ github.event.release.tag_name }}
        file: v1.4-alpha.zip

    - name: Print working directory
      run: pwd

    - name: List files in current directory
      run: ls -la


    - name: Unzip release asset
      run: unzip kcctl.zip -d kcctl

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: mdwajid095
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./kcctl
        push: true
        tags: mdwajid095/kcctl:${{ github.event.release.tag_name }}
