name: Build and Push Docker Image on New Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download specific file
      run: |
        wget https://github.com/mdwajid095/kcctl/archive/refs/tags/${{ github.event.release.tag_name }}.tar.gz
        tar -xzvf ${{ github.event.release.tag_name }}.tar.gz
        pwd
        ls

    - name: Download release asset
      uses: i3h/download-release-asset@v1
      with:
        owner: mdwajid095
        repo: kcctl
        tag: ${{ github.event.release.tag_name }}
        file: ${{ github.event.release.tag_name }}.zip
        path: .

    - name: Unzip release asset
      run: unzip ${{ github.event.release.tag_name }}.zip -d ${{ github.event.release.tag_name }}

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: mdwajid095
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./kcctl
        push: true
        tags: mdwajid095/kcctl:${{ github.event.release.tag_name }}
